server:
  port: 8082
  tomcat:
    threads:
      max: 50
    accept-count: 50
    maxconnections: 100

feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车接口文档"
    package: com.hmall.cart.controller

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 保安队长的地址
      http-method-specify: true # 是否设置请求方式作为资源名称
